# syntax=docker/dockerfile:1.7

FROM node:22-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --include=dev --no-audit --no-fund

FROM node:22-slim AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# NEXT_PUBLIC_* values are inlined into the client bundle at build time, so they
# must be supplied as build args (Dokploy: Advanced > Build Args).
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_AUTH_GOOGLE_ID
ARG NEXT_PUBLIC_APPLE_SIGNIN_ENABLED
ARG NEXT_PUBLIC_AUTH_APPLE_ANDROID_CLIENT_ID
ARG NEXT_PUBLIC_APPLE_APP_ID
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE
ARG NEXT_PUBLIC_SENTRY_REPLAY_SESSION_SAMPLE_RATE
ARG NEXT_PUBLIC_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE
ARG NEXT_PUBLIC_APP_BUILD_ID
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_AUTH_GOOGLE_ID=$NEXT_PUBLIC_AUTH_GOOGLE_ID \
    NEXT_PUBLIC_APPLE_SIGNIN_ENABLED=$NEXT_PUBLIC_APPLE_SIGNIN_ENABLED \
    NEXT_PUBLIC_AUTH_APPLE_ANDROID_CLIENT_ID=$NEXT_PUBLIC_AUTH_APPLE_ANDROID_CLIENT_ID \
    NEXT_PUBLIC_APPLE_APP_ID=$NEXT_PUBLIC_APPLE_APP_ID \
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID \
    NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION \
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE \
    NEXT_PUBLIC_SENTRY_REPLAY_SESSION_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_REPLAY_SESSION_SAMPLE_RATE \
    NEXT_PUBLIC_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE \
    NEXT_PUBLIC_APP_BUILD_ID=$NEXT_PUBLIC_APP_BUILD_ID

COPY --from=deps /app/node_modules ./node_modules
COPY . .
# build:ci = next build only (build/build:next restart PM2 / read .env for the host deploy)
RUN --mount=type=cache,target=/app/.next/cache \
    npm run build:ci

FROM node:22-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# next.config.ts is loaded at start, which needs typescript, so dev deps stay.
COPY --from=build /app ./

EXPOSE 3000
CMD ["node", "scripts/start-next.js"]
